"""empty message

Revision ID: 1ce514e64788
Revises: 88245b238ef3
Create Date: 2017-07-25 04:57:38.144285

"""

# revision identifiers, used by Alembic.
revision = '1ce514e64788'
down_revision = '88245b238ef3'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('art_file', 'fspath',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('art_item', 'artist_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_art_item_release_meta'), 'art_item', ['release_meta'], unique=False)
    op.drop_index('art_item_artist_id_release_meta_idx', table_name='art_item')
    op.drop_index('art_item_release_meta_idx', table_name='art_item')
    op.add_column('scrape_targets', sa.Column('extra_meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('scrape_targets', sa.Column('release_cnt', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scrape_targets_artist_name'), 'scrape_targets', ['artist_name'], unique=False)
    op.drop_index('scrape_targets_artist_name_idx', table_name='scrape_targets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('scrape_targets_artist_name_idx', 'scrape_targets', ['artist_name'], unique=False)
    op.drop_index(op.f('ix_scrape_targets_artist_name'), table_name='scrape_targets')
    op.drop_column('scrape_targets', 'release_cnt')
    op.drop_column('scrape_targets', 'extra_meta')
    op.create_index('art_item_release_meta_idx', 'art_item', ['release_meta'], unique=False)
    op.create_index('art_item_artist_id_release_meta_idx', 'art_item', ['artist_id', 'release_meta'], unique=False)
    op.drop_index(op.f('ix_art_item_release_meta'), table_name='art_item')
    op.alter_column('art_item', 'artist_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('art_file', 'fspath',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
