"""empty message

Revision ID: 2a79e1a92e89
Revises: 1ce514e64788
Create Date: 2017-07-27 05:19:18.251598

"""

# revision identifiers, used by Alembic.
revision = '2a79e1a92e89'
down_revision = '1ce514e64788'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_item', sa.Column('content_structured', sqlalchemy_jsonfield.JSONField(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art_item', 'content_structured')
    # ### end Alembic commands ###
