"""empty message

Revision ID: 48f7ba9d85fe
Revises: 6ac11f48bcca
Create Date: 2017-07-29 03:00:00.771211

"""

# revision identifiers, used by Alembic.
revision = '48f7ba9d85fe'
down_revision = '6ac11f48bcca'

from alembic import op
import sqlalchemy as sa
import settings


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if settings.SQLALCHEMY_DATABASE_URI.startswith("sqlite://"):
        print("Ok SQLITE is properly annoying now")
    else:
        op.drop_column('art_file', 'fqurl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_file', sa.Column('fqurl', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
