"""empty message

Revision ID: 6ac11f48bcca
Revises: 355a8f844fb8
Create Date: 2017-07-28 08:37:18.331918

"""

# revision identifiers, used by Alembic.
revision = '6ac11f48bcca'
down_revision = '355a8f844fb8'

from alembic import op
import sqlalchemy as sa
import settings


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_file', sa.Column('file_meta', sa.Text(), nullable=True))
    if settings.SQLALCHEMY_DATABASE_URI.startswith("sqlite://"):
        print("Skipping MORE stuff due to sqlite limitations.")
    else:
        op.drop_constraint('art_file_item_id_seqnum_key', 'art_file', type_='unique')
        op.create_unique_constraint(None, 'art_file', ['item_id', 'seqnum', 'file_meta'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'art_file', type_='unique')
    op.create_unique_constraint('art_file_item_id_seqnum_key', 'art_file', ['item_id', 'seqnum'])
    op.drop_column('art_file', 'file_meta')
    ### end Alembic commands ###
