"""Add kv store table

Revision ID: 80b62107850a
Revises: df882e0d4494
Create Date: 2022-04-04 00:10:01.576302

"""

# revision identifiers, used by Alembic.
revision = '80b62107850a'
down_revision = 'df882e0d4494'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value_store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_value_store_key'), 'key_value_store', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_value_store_key'), table_name='key_value_store')
    op.drop_table('key_value_store')
    # ### end Alembic commands ###
