"""empty message

Revision ID: 916e4599f92d
Revises: 8e7013c7db9b
Create Date: 2017-12-10 20:06:59.409760

"""

# revision identifiers, used by Alembic.
revision = '916e4599f92d'
down_revision = '8e7013c7db9b'

from alembic import op
import sqlalchemy as sa
import json

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	conn = op.get_bind()
	pat_releases = conn.execute("SELECT id, release_meta FROM art_item WHERE artist_id IN (SELECT id FROM scrape_targets WHERE site_name='pat')")

	# This is dumb, but I should have used a tuple from the outset, because I need to be able to put
	# the release items in a set for various reasons.
	for rid, postid in pat_releases:
		post_params = json.loads(postid)
		new_post = json.dumps((post_params['type'],  post_params['id']))
		changed = conn.execute("UPDATE art_item SET release_meta = %s WHERE id = %s", (new_post, rid))
		if changed.rowcount == 1:
			print(".", end="", flush=True)
		else:
			print("X", end="", flush=True)



def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
