"""empty message

Revision ID: 94e00cbf879f
Revises: 6937420ccb1b
Create Date: 2017-07-15 15:32:59.970894

"""

# revision identifiers, used by Alembic.
revision = '94e00cbf879f'
down_revision = '6937420ccb1b'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('prev_run', sa.DateTime(), nullable=False),
    sa.Column('prev_run_time', sa.Interval(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('status_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_status_id'), 'scraper_status', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_status_site_name'), 'scraper_status', ['site_name'], unique=True)
    ### end Alembic commands ###


def downgrade():

    op.drop_index(op.f('ix_scraper_status_site_name'), table_name='scraper_status')
    op.drop_index(op.f('ix_scraper_status_id'), table_name='scraper_status')
    op.drop_table('scraper_status')
    ### end Alembic commands ###
