"""Add artist enable column

Revision ID: 9a7aef735c43
Revises: 80b62107850a
Create Date: 2022-04-25 09:37:30.549193

"""

# revision identifiers, used by Alembic.
revision = '9a7aef735c43'
down_revision = '80b62107850a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_targets', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE scrape_targets SET enabled = true")
    op.alter_column('scrape_targets', 'enabled', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_targets', 'enabled')
    # ### end Alembic commands ###
