"""empty message

Revision ID: c45d541f4ce1
Revises: 48f7ba9d85fe
Create Date: 2017-09-04 08:08:10.543592

"""

# revision identifiers, used by Alembic.
revision = 'c45d541f4ce1'
down_revision = '48f7ba9d85fe'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_targets', sa.Column('in_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_targets', 'in_progress')
    # ### end Alembic commands ###
