"""Re-Scrape pixiv since manga item scraping was broken

Revision ID: df882e0d4494
Revises: 46e1cef59e06
Create Date: 2020-03-15 00:39:03.108221

"""

# revision identifiers, used by Alembic.
revision = 'df882e0d4494'
down_revision = '46e1cef59e06'

from alembic import op
import sqlalchemy as sa


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###

	conn = op.get_bind()
	conn.execute("UPDATE art_item SET state='new' WHERE artist_id IN (SELECT id FROM scrape_targets WHERE site_name='px')")
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
