"""empty message

Revision ID: eadf6d98df7c
Revises: 2a79e1a92e89
Create Date: 2017-07-27 05:58:32.372896

"""

# revision identifiers, used by Alembic.
revision = 'eadf6d98df7c'
down_revision = '2a79e1a92e89'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_file', sa.Column('fqurl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art_file', 'fqurl')
    # ### end Alembic commands ###
