"""empty message

Revision ID: f058fce52fad
Revises: c45d541f4ce1
Create Date: 2017-10-19 04:30:15.589618

"""

# revision identifiers, used by Alembic.
revision = 'f058fce52fad'
down_revision = 'c45d541f4ce1'

from alembic import op
import sqlalchemy as sa
import settings


def upgrade():
	if not settings.SQLALCHEMY_DATABASE_URI.startswith("sqlite://"):
		# ### commands auto generated by Alembic - please adjust! ###
		conn = op.get_bind()

		print("Getting timestamps")
		moar = conn.execute("""
			SELECT
				id,
				fetchtime,
				addtime
			FROM
				art_item
			WHERE
				addtime < '1/1/1000'::timestamp
			""")
		res1 = moar.fetchall()

		print("Found %s items" % len(res1))
		fixed = 0
		for item in res1:
			conn.execute("""
				UPDATE
					art_item
				SET
					addtime = %s
				WHERE
					id = %s
				""", (item[1], item[0]))
			fixed += 1
			if fixed % 1000 == 0:
				print("Fixed %s of %s items" % (fixed, len(res1)))

		print("Fixing complete. Validating")


		moar = conn.execute("""
			SELECT
				id,
				fetchtime,
				addtime
			FROM
				art_item
			WHERE
				addtime < '1/1/1000'::timestamp
			""")
		res2 = moar.fetchall()

		print("%s items that still predate year 1000." % len(res2))



def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
