"""empty message

Revision ID: 6ac11f48bcca
Revises: None
Create Date: 2017-11-29 07:15:20.572304

"""

# revision identifiers, used by Alembic.
revision = '6ac11f48bcca'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('artist_name', sa.Text(), nullable=False),
    sa.Column('uploadeh', sa.Boolean(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=False),
    sa.Column('extra_meta', sqlalchemy_jsonfield.JSONField(), nullable=True),
    sa.Column('release_cnt', sa.Integer(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name', 'artist_name')
    )
    op.create_index(op.f('ix_scrape_targets_artist_name'), 'scrape_targets', ['artist_name'], unique=False)
    op.create_index(op.f('ix_scrape_targets_uploadeh'), 'scrape_targets', ['uploadeh'], unique=False)
    op.create_table('scraper_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('prev_run', sa.DateTime(), nullable=False),
    sa.Column('prev_run_time', sa.Interval(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('status_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_status_id'), 'scraper_status', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_status_site_name'), 'scraper_status', ['site_name'], unique=True)
    op.create_table('art_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('new', 'fetching', 'processing', 'complete', 'error', 'removed', 'disabled', 'specialty_deferred', 'specialty_ready', 'not_set', name='dlstate_enum'), nullable=False),
    sa.Column('errno', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.BigInteger(), nullable=False),
    sa.Column('release_meta', sa.Text(), nullable=False),
    sa.Column('fetchtime', sa.DateTime(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_structured', sqlalchemy_jsonfield.JSONField(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['scrape_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'release_meta')
    )
    op.create_index(op.f('ix_art_item_id'), 'art_item', ['id'], unique=False)
    op.create_index(op.f('ix_art_item_release_meta'), 'art_item', ['release_meta'], unique=False)
    op.create_index(op.f('ix_art_item_state'), 'art_item', ['state'], unique=False)
    op.create_table('art_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('seqnum', sa.Integer(), nullable=False),
    sa.Column('file_meta', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('new', 'fetching', 'processing', 'complete', 'error', 'removed', 'disabled', 'specialty_deferred', 'specialty_ready', 'not_set', name='dlstate_enum'), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['art_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'seqnum', 'file_meta')
    )
    op.create_index(op.f('ix_art_file_id'), 'art_file', ['id'], unique=False)
    op.create_table('art_tag',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['art_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'tag')
    )
    op.create_index(op.f('ix_art_tag_id'), 'art_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_art_tag_id'), table_name='art_tag')
    op.drop_table('art_tag')
    op.drop_index(op.f('ix_art_file_id'), table_name='art_file')
    op.drop_table('art_file')
    op.drop_index(op.f('ix_art_item_state'), table_name='art_item')
    op.drop_index(op.f('ix_art_item_release_meta'), table_name='art_item')
    op.drop_index(op.f('ix_art_item_id'), table_name='art_item')
    op.drop_table('art_item')
    op.drop_index(op.f('ix_scraper_status_site_name'), table_name='scraper_status')
    op.drop_index(op.f('ix_scraper_status_id'), table_name='scraper_status')
    op.drop_table('scraper_status')
    op.drop_index(op.f('ix_scrape_targets_uploadeh'), table_name='scrape_targets')
    op.drop_index(op.f('ix_scrape_targets_artist_name'), table_name='scrape_targets')
    op.drop_table('scrape_targets')
    # ### end Alembic commands ###
